### ISSUE TITLE
Was there a server issue preventing the delivery of requested test certificates to the client?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-dcc-server#37]
## Your Question

Hi, a Twitter user reported that he wasn't able to get his requested test certificate today. For 6 hours his CWA showed that the certificate is not yet ready. Was there a server issue today?

**Comment by f11h** [comment]
Hi Tim, can you confirm that the user had the problems on 10.07.2021 and not on 09.07.2021?

**Comment by Ein-Tim** [comment]
@f11h 

Yes, I can confirm this.

**Comment by f11h** [comment]
Yes we had some problems on 09.07 for some hours.

**Comment by Ein-Tim** [comment]
@f11h 

Okay thanks for the feedback!
