### ISSUE TITLE
Certificate chain is incomplete

### ISSUE THREAD

**Issue by FloEc** [corona-warn-app/cwa-dcc-server#38]
## Describe the bug

The certificate chain for the productive server is not complete. For the WRU environment, the certificate chain is complete.
WRU: 
https://www.ssllabs.com/ssltest/analyze.html?d=dcc-proxy-cff4f7147260.coronawarn.app&hideResults=on
PROD:
https://www.ssllabs.com/ssltest/analyze.html?d=dcc-proxy.coronawarn.app&hideResults=on

## Expected behaviour

Complete certificate chain on the productive environment.

## Steps to reproduce the issue

Performing an SSL check.

Alternatively, when connecting with Java, the intermediate certificate must be explicitly included in the trust store for the connection to be successful.

## Possible Fix

Adaptation of the SSL configuration as in the WRU environment..

**Comment by f11h** [comment]
Hello @FloEc ,

The DCC-Proxy service is only accessible through a mTLS secured connection. To ensure E2E trust our partners are asked to youse a dedicated TrustStore for the connection to DCC-Proxy. But nevertheless I will forward this to our Ops team so that they can analyze whether they will add the intermediate CA to the chain.

**Comment by KDederichs** [comment]
Oh yeah I’ve run into that as well actually….
I was wondering if you needed some extra CA for the Prod server cause even if you try to connect to it via mTLS (using Curl) it will just throw an exception with:
`SSL certificate problem: unable to get local issuer certificate`

In case of curl you can disable the CA check and it will work but I’m sure that’s not what’s intended.

**Comment by KDederichs** [comment]
https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/H%C3%A4ufige-Fehler#die-verbindung-zur-produktivumgebung-schl%C3%A4gt-fehl ok it DOES have a custom one....
You REALLY need to add that to the implementation instructions and not hide it in the errors tab....

**Comment by f11h** [comment]
Can you please check again?

**Comment by bszalayn** [comment]
Hi guys,
Now the full chain is visible.

**Comment by FloEc** [comment]
Hi @f11h,

looks good now. 
Thank you for your help.
