### ISSUE TITLE
What does the DCC_COMP_202 error mean? 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-dcc-server#39]
## Your Question

This question is related to https://github.com/corona-warn-app/cwa-app-ios/issues/3256.

What does the DCC_COMP_202 error mean?

**Comment by f11h** [comment]
Hello Tim,

the error code itself is generated by the iOS App. I don't know what it maps to. So you have to wait until you get a more technical response in the original ticket.

I would assume, that it has to do something with the compression of the DCC.

**Comment by Ein-Tim** [comment]
@f11h 

Okay, thank you!
