### ISSUE TITLE
Das "technische Ablaufdatum" wird aktuell bei den Schnelltestzertifikaten auf 24Stunden gesetzt, selbst wenn die Zertifikate bei der Einreise 48h oder 72h gültig sind.

### ISSUE THREAD

**Issue by Rhglomb** [corona-warn-app/cwa-dcc-server#44]
Das "technische Ablaufdatum" der aktuell in Deutschland ausgestellten Schnelltestzertifikate, wird aktuell bei den Schnelltestzertifikaten auf 24Stunden gesetzt. In den CovicCheck Apps, auch der französischen, führt das dazu, dass das Zertifikat nach 24h als nicht mehr Gültig angesehen wird.
Selbst wenn z.B. in Frankreich zur Einreise ein Schnelltest 72h alt sein darf, zeigen die deutschen und auch die französische App diesen Test als "Abgelaufen an.

Lösung: Entweder die Technische Gültigkeit der Testzertifikate auf mindestens 1 Woche setzen (bevorzugt, da diese Änderung nur bei der Zertifikatserstellung gemacht werden muss).
oder alle Apps müssen das "Technische Ablaufdatum" für Testzertifikate ignorieren.

 Um die ursprüngliche Idee des "Technischen Ablaufdatums" zu erhalten, macht nur Variante 1 wirklich Sinn. Das technische Ablaufdatum soll definieren, ab wann ein Zertifikat nicht mehr gültig ist, aber nicht, ab wann der durchgeführte Test nicht anerkannt werden darf, denn das ist je Land/Bundesland/Verwendungszweck unterschiedlich und volatil.

Das "Technische Ablaufdatum" muss völlig losgelöst von der Aktzeptanzzeit des Schnelltestergebnisses sein. Dieses Datum ist auch ursprünglich für den Impf/Genesenennachweis gedacht gewesen. 

Der aktuelle Zustand ist fatal, da er aktuell viele Reisende vor Probleme stellt und verunsichert. Insbesondere da gültige Testzertifikate von den Apps als ungültig bzw. abgelaufen angezeigt werden.

**Comment by Ein-Tim** [comment]
Related issue:
- https://github.com/corona-warn-app/cwa-wishlist/issues/526

**Comment by f11h** [comment]
Hallo @Rhglomb ,

das von dir beschriebene Problem ist konzeptueller Natur und liegt nicht im Verantwortungsbereich des CWA-DCC-Servers. @Ein-Tim hat ja bereits das korrekte Issue verlinkt. Daher schließe ich dieses hier.
